### ISSUE TITLE
Explain use of color in text (example Figure 1.6), think about grey scale printing

### ISSUE THREAD

**Issue by MethDamon** [abaumeler/ineco#7]
Wenn Ihr in Graphiken Farben erwendet, bedenkt schwarz/weiß Druck und erklärt auch die Bedeutung im Text (bspw. Figure 1.6)

**Comment by MethDamon** [comment]
![bildschirmfoto 2016-01-14 um 11 29 22](https://cloud.githubusercontent.com/assets/5677852/12322062/2ef2257e-bab2-11e5-894a-17649dddb9fc.png)
![bildschirmfoto 2016-01-14 um 11 29 28](https://cloud.githubusercontent.com/assets/5677852/12322063/2ef44dd6-bab2-11e5-8955-cb4c64bfe09d.png)
![bildschirmfoto 2016-01-14 um 11 29 35](https://cloud.githubusercontent.com/assets/5677852/12322064/2ef75fd0-bab2-11e5-911e-a5fb9571a7c0.png)
![bildschirmfoto 2016-01-14 um 11 29 42](https://cloud.githubusercontent.com/assets/5677852/12322065/2ef95510-bab2-11e5-9c66-6083f7282f40.png)
![bildschirmfoto 2016-01-14 um 11 29 48](https://cloud.githubusercontent.com/assets/5677852/12322066/2efc0bca-bab2-11e5-9f52-36231810bd99.png)
![bildschirmfoto 2016-01-14 um 11 29 54](https://cloud.githubusercontent.com/assets/5677852/12322067/2eff06cc-bab2-11e5-8f92-46b153431450.png)

Das sind alle Grafiken in Grey Scale, findet ihr eins unverständlich davon, eventuell könnte man die Private/Public Keys in der grossen Übersicht noch klarer machen. Aber finde ich jetzt nicht nötig.

**Comment by abaumeler** [comment]
Finde die Grafiken so ok :+1:
